In [14]:
import numpy as np
import random as r
# below code can be used to generate all the permutation matrices

# size of the matrices
size = 4
# below is the code segment to compare 2 matrices
def areSame(A,B):

    for i in range(size):
        for j in range(size):
            if (A[i,j] != B[i,j]):
                return 0
    return 1

# below are our generating matrices

a = np.matrix('0 1 0 0; 1 0 0 0; 0 0 1 0; 0 0 0 1')
b = np.matrix('1 0 0 0; 0 0 1 0; 0 1 0 0; 0 0 0 1')
c = np.matrix('1 0 0 0; 0 1 0 0; 0 0 0 1; 0 0 1 0')
d = np.matrix('0 0 0 1; 0 1 0 0; 0 0 1 0; 1 0 0 0')


perm = []
sample = [a,b,c,d]

product = np.matrix('1 0 0 0; 0 1 0 0; 0 0 1 0; 0 0 0 1')


count = 0
while count < 1000:
    count2 = 0
    add = 1
    while count2 < len(perm):

        if areSame(product,perm[count2]) == 1:
            add = 0 
        count2 = count2 + 1
    if add == 1:
        perm.append(product)
    
    random = r.choice(sample)
    product = np.dot(product,random)
    count = count + 1


In [15]:
i = 0
while i < len(perm):
    print("   ")
    print(perm[i])
    print(".............")
    i = i + 1
    
len(perm)

   
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
.............
   
[[0 0 0 1]
 [0 1 0 0]
 [0 0 1 0]
 [1 0 0 0]]
.............
   
[[0 0 1 0]
 [0 1 0 0]
 [0 0 0 1]
 [1 0 0 0]]
.............
   
[[0 0 1 0]
 [1 0 0 0]
 [0 0 0 1]
 [0 1 0 0]]
.............
   
[[0 0 0 1]
 [1 0 0 0]
 [0 0 1 0]
 [0 1 0 0]]
.............
   
[[0 0 0 1]
 [1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]
.............
   
[[0 0 0 1]
 [0 1 0 0]
 [1 0 0 0]
 [0 0 1 0]]
.............
   
[[0 0 1 0]
 [0 1 0 0]
 [1 0 0 0]
 [0 0 0 1]]
.............
   
[[0 1 0 0]
 [0 0 1 0]
 [1 0 0 0]
 [0 0 0 1]]
.............
   
[[0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]
 [1 0 0 0]]
.............
   
[[1 0 0 0]
 [0 0 1 0]
 [0 1 0 0]
 [0 0 0 1]]
.............
   
[[0 0 0 1]
 [0 0 1 0]
 [0 1 0 0]
 [1 0 0 0]]
.............
   
[[1 0 0 0]
 [0 0 0 1]
 [0 0 1 0]
 [0 1 0 0]]
.............
   
[[1 0 0 0]
 [0 0 0 1]
 [0 1 0 0]
 [0 0 1 0]]
.............
   
[[0 1 0 0]
 [0 0 0 1]
 [1 0 0 0]
 [0 0 1 0]]
.............
   
[[0 0 1 0]
 [0 0 0 1]
 [1 0 0 0]
 [0 1 0 0]]
......

24

In [10]:
import numpy as np
import random as r

# size of the matrices = 5*%

size = 5



# below are our generating matrices

a = np.matrix('0 1 0 0 0; 1 0 0 0 0; 0 0 1 0 0; 0 0 0 1 0; 0 0 0 0 1')
b = np.matrix('1 0 0 0 0; 0 0 1 0 0; 0 1 0 0 0; 0 0 0 1 0; 0 0 0 0 1')
c = np.matrix('1 0 0 0 0; 0 1 0 0 0; 0 0 0 1 0; 0 0 1 0 0; 0 0 0 0 1')
d = np.matrix('1 0 0 0 0; 0 1 0 0 0; 0 0 1 0 0; 0 0 0 0 1; 0 0 0 1 0')
e = np.matrix('0 0 0 0 1; 0 1 0 0 0; 0 0 1 0 0; 0 0 0 1 0; 1 0 0 0 0')


perm = []
sample = [a,b,c,d,e]

product = np.matrix('1 0 0 0 0; 0 1 0 0 0; 0 0 1 0 0; 0 0 0 1 0; 0 0 0 0 1')


count = 0
while count < 10000:
    count2 = 0
    add = 1
    while count2 < len(perm):

        if areSame(product,perm[count2]) == 1:
            add = 0 
        count2 = count2 + 1
    if add == 1:
        perm.append(product)
    
    random = r.choice(sample)
    product = np.dot(product,random)
    count = count + 1



In [11]:

len(perm)

120

In [6]:
size = 3



# below are our generating matrices

a = np.matrix('0 1 0; 1 0 0; 0 0 1')
b = np.matrix('1 0 0; 0 0 1; 0 1 0')
c = np.matrix('0 0 1 ; 0 1 0; 1 0 0')



perm = []
sample = [a,b,c]

product = np.matrix('1 0 0; 0 1 0; 0 0 1')


count = 0
while count < 1000:
    count2 = 0
    add = 1
    while count2 < len(perm):

        if areSame(product,perm[count2]) == 1:
            add = 0 
        count2 = count2 + 1
    if add == 1:
        perm.append(product)
    
    random = r.choice(sample)
    product = np.dot(product,random)
    count = count + 1



In [7]:
len(perm)

6

In [3]:
# Breaking into various pieces for 3*3

# below code can be used to generate all the permutation matrices
import numpy as np 
import random as r
# size of the matrices
size = 3
# below is the code segment to compare 2 matrices
def areSame(A,B):

    for i in range(size):
        for j in range(size):
            if (A[i,j] != B[i,j]):
                return 0
    return 1

a = np.matrix('0 1 0; 1 0 0; 0 0 1')
b = np.matrix('1 0 0; 0 0 1; 0 1 0')
c = np.matrix('0 0 1 ; 0 1 0; 1 0 0')



perm = []
sample = [a,b,c]

product = np.matrix('1 0 0; 0 1 0; 0 0 1')


    

add = 1
count3 = 0
while count3< 10000:
    count = 0
    product = np.matrix('1 0 0; 0 1 0; 0 0 1')
    while count < 102:
        product = np.dot(product, r.choice(sample))
        count = count + 1
    add = 1
    count2 = 0
    while count2 < len(perm):
    
        if areSame(product,perm[count2]) == 1:
            add = 0 
        count2 = count2 + 1
    if add == 1:
        perm.append(product)
    count3 = count3 + 1
 

In [26]:
print(perm)
len(perm)

[matrix([[1, 0, 0],
        [0, 0, 1],
        [0, 1, 0]]), matrix([[0, 0, 1],
        [0, 1, 0],
        [1, 0, 0]]), matrix([[0, 1, 0],
        [1, 0, 0],
        [0, 0, 1]])]


3

In [46]:
# Breaking into various pieces for 4*4
# below code can be used to generate all the permutation matrices

# size of the matrices

size = 4

# below is the code segment to compare 2 matrices

def areSame(A,B):

    for i in range(size):
        for j in range(size):
            if (A[i,j] != B[i,j]):
                return 0
    return 1


perm = []


product = np.matrix('1 0 0 0; 0 1 0 0; 0 0 1 0; 0 0 0 1')

a = np.matrix('0 1 0 0; 1 0 0 0; 0 0 1 0; 0 0 0 1')
b = np.matrix('1 0 0 0; 0 0 1 0; 0 1 0 0; 0 0 0 1')
c = np.matrix('1 0 0 0; 0 1 0 0; 0 0 0 1; 0 0 1 0')
d = np.matrix('0 0 0 1; 0 1 0 0; 0 0 1 0; 1 0 0 0')
sample = [a,b,c,d]    

add = 1
count3 = 0

while count3< 10000:
    count = 0
    product = np.matrix('1 0 0 0; 0 1 0 0; 0 0 1 0; 0 0 0 1')
    while count < 4:
        product = np.dot(product, r.choice(sample))
        count = count + 1
    add = 1
    count2 = 0
    while count2 < len(perm):
    
        if areSame(product,perm[count2]) == 1:
            add = 0 
        count2 = count2 + 1
    if add == 1:
        perm.append(product)
    count3 = count3 + 1
 

In [47]:
print(perm)
len(perm)

[matrix([[1, 0, 0, 0],
        [0, 0, 1, 0],
        [0, 0, 0, 1],
        [0, 1, 0, 0]]), matrix([[0, 1, 0, 0],
        [0, 0, 0, 1],
        [0, 0, 1, 0],
        [1, 0, 0, 0]]), matrix([[0, 1, 0, 0],
        [1, 0, 0, 0],
        [0, 0, 0, 1],
        [0, 0, 1, 0]]), matrix([[0, 0, 0, 1],
        [0, 0, 1, 0],
        [0, 1, 0, 0],
        [1, 0, 0, 0]]), matrix([[0, 0, 1, 0],
        [1, 0, 0, 0],
        [0, 1, 0, 0],
        [0, 0, 0, 1]]), matrix([[0, 0, 0, 1],
        [0, 1, 0, 0],
        [1, 0, 0, 0],
        [0, 0, 1, 0]]), matrix([[1, 0, 0, 0],
        [0, 1, 0, 0],
        [0, 0, 1, 0],
        [0, 0, 0, 1]]), matrix([[0, 0, 1, 0],
        [0, 0, 0, 1],
        [1, 0, 0, 0],
        [0, 1, 0, 0]]), matrix([[0, 1, 0, 0],
        [0, 0, 1, 0],
        [1, 0, 0, 0],
        [0, 0, 0, 1]]), matrix([[0, 0, 1, 0],
        [0, 1, 0, 0],
        [0, 0, 0, 1],
        [1, 0, 0, 0]]), matrix([[1, 0, 0, 0],
        [0, 0, 0, 1],
        [0, 1, 0, 0],
        [0, 0, 1, 0]]), matrix([[

12

In [ ]:
print(perm)